# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  sqlconn: '$(sqlconnectionstrvar)'
  cosmosendpoint: '$(cosmosendpointvar)'
  cosmosauthkey: '$(cosmosauthkeyvar)'
  storageaccconnstrvar: '$(storageaccconnstr)'
  azservicebusconnstrvar: '$(azservicebusconnstr)'
  kbntsnamespacevar: '$(namespacevar)'

steps:
- script: |
    echo "Replacing {{sqlconnectionstrvar}} in deployment.yaml with $(sqlconn)"
    sed -i 's/{{sqlconnectionstrvar}}/$(sqlconn)/g' secret.yaml
    echo "Replacing {{cosmosendpointvar}} in deployment.yaml with $(cosmosendpoint)"
    sed -i 's/{{cosmosendpointvar}}/$(cosmosendpoint)/g' secret.yaml
    echo "Replacing {{cosmosauthkeyvar}} in deployment.yaml with $(cosmosauthkey)"
    sed -i 's/{{cosmosauthkeyvar}}/$(cosmosauthkey)/g' secret.yaml
    echo "Replacing {{storageauthkeyvar}} in deployment.yaml with $(storageaccconnstrvar)"
    sed -i 's/{{storageauthkeyvar}}/$(storageaccconnstrvar)/g' secret.yaml
    echo "Replacing {{azservicebusconnstrvar}} in deployment.yaml with $(azservicebusconnstrvar)"
    sed -i 's/{{azservicebusconnstrvar}}/$(azservicebusconnstrvar)/g' secret.yaml  
    echo "Replacing {{namespacevar}} in deployment.yaml with $(kbntsnamespacevar)"
    sed -i 's/{{namespacevar}}/$(kbntsnamespacevar)/g' secret.yaml  
  displayName: Replace tag secret.yaml

- task: Kubernetes@1
  displayName: Apply secret.yaml
  inputs:
    kubernetesServiceEndpoint: 'az-k8s-easy-kart'
    namespace: '$(kbntsnamespacevar)'
    command: 'apply'
    arguments: '-f secret.yaml'

